In [2]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("anime.csv")

In [8]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

## Make a new Column for episode count

In [14]:
df.loc[2]["Title"]

'Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members'

In [38]:
def extract_episodes(txt):
    check = False
    data = ""
    
    for i in txt:
        if i == ")":
            break
        if i == '(':
            check = True
        if check == True and i != '(':
            data += i
    ans = data.replace(" eps", "")
    return int(ans)

In [39]:
df["Episodes"] = df["Title"].apply(extract_episodes)

## Make a new Column for time stamp

In [44]:
df.loc[44]["Title"]

'Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 202255,833 members'

In [52]:
def extract_timeStamp(txt):
    for i in range(0, len(txt)):
        if txt[i] == ')':
            return txt[i+1 : i+20]

    return ""

In [56]:
df["Timestamps"] = df["Title"].apply(extract_timeStamp)

In [70]:
df.head()

,Rank,Title,Score,Episodes,Timestamps
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

## Which Anime has the highest Score

In [66]:
highest_score = df[df["Score"] == df["Score"].max()]

In [67]:
highest_score

,Rank,Title,Score,Episodes,Timestamps
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 2010

## Give me Top 5 Highest Scoring anime

In [71]:
df["Title"].head()

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: str

## Which Anime has the Highest episode count?

In [72]:
df[df["Episodes"] == df["Episodes"].max()]

,Rank,Title,Score,Episodes,Timestamps
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010

## Animes with top 5 episode count

In [79]:
df["Episodes"].values

array([ 64,  24,  13,  51,  10,  51,   1, 148,  13,  13,   2, 110,  13,
        13,  12, 201,   1,  22,  24,  25,   1,   1,   7,  14,  74,   1,
         1,  12,   1,  24,  23,  12,  26,  13,  16,  11,   1,  11,  10,
         1,  26,  12,  75,  26,  26,  24,  10,  12,  12,   4])

In [82]:
top_5_episodes = df.nlargest(5, 'Episodes')
top_5_episodes

,Rank,Title,Score,Episodes,Timestamps
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005

## Which is the Longest running anime

In [89]:
def calculate_run_duration(ts):
    start_str, end_str = ts.split(' - ')
    start = pd.to_datetime(start_str.strip())
    end = pd.to_datetime(end_str.strip())
        
    return (end - start).days

df['Run_Duration'] = df['Timestamps'].apply(calculate_run_duration)

In [90]:
df.head()

,Rank,Title,Score,Episodes,Timestamps,Run_Duration
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,456
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,153
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,61
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,335
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,91

In [91]:
df[df["Run_Duration"] == df["Run_Duration"].max()]

,Rank,Title,Score,Episodes,Timestamps,Run_Duration
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,3347