In [3]:
import numpy as np
import pandas as pd

# Series

In [4]:
data_list = [10, 20, 30, 40, 50]
labels=['a', 'b', 'c', 'd', 'e']

In [5]:
pd.Series(data_list)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [6]:
pd.Series(data_list, index=labels)

a    10
b    20
c    30
d    40
e    50
dtype: int64

# Data Frames

In [7]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 28, 22],
    'City': ['New York', 'London', 'Paris', 'Tokyo', 'Mumbai'],
    'Salary': [70000, 85000, 95000, 62000, 58000]
}

In [8]:
df = pd.DataFrame(data)
df

      Name  Age      City  Salary
0    Alice   25  New York   70000
1      Bob   30    London   85000
2  Charlie   35     Paris   95000
3    David   28     Tokyo   62000
4      Eve   22    Mumbai   58000

In [48]:
data = [
    ['Alice', 25, 'New York', 70000],
    ['Bob', 30, 'London', 85000],
    ['Charlie', 35, 'Paris', 95000],
    ['David', 28, 'Tokyo', 62000],
    ['Eve', 22, 'Mumbai', 58000]
]

In [49]:
columns = ["Name", "Age", "City", "Salary"]
df = pd.DataFrame(data_array, columns=columns)
df

      Name Age      City Salary
0    Alice  25  New York  70000
1      Bob  30    London  85000
2  Charlie  35     Paris  95000
3    David  28     Tokyo  62000
4      Eve  22    Mumbai  58000

### Selection and indexing of Columns

In [50]:
df[["Name", "City"]]

      Name      City
0    Alice  New York
1      Bob    London
2  Charlie     Paris
3    David     Tokyo
4      Eve    Mumbai

### Creating a new Columns

In [51]:
df["Destination"] = ["Berlin", "Madrid", "Rome", "Sydney", "Toronto"]
df

      Name Age      City Salary Destination
0    Alice  25  New York  70000      Berlin
1      Bob  30    London  85000      Madrid
2  Charlie  35     Paris  95000        Rome
3    David  28     Tokyo  62000      Sydney
4      Eve  22    Mumbai  58000     Toronto

### Removing

In [52]:
df.drop("Destination", axis=1)

      Name Age      City Salary
0    Alice  25  New York  70000
1      Bob  30    London  85000
2  Charlie  35     Paris  95000
3    David  28     Tokyo  62000
4      Eve  22    Mumbai  58000

In [53]:
df

      Name Age      City Salary Destination
0    Alice  25  New York  70000      Berlin
1      Bob  30    London  85000      Madrid
2  Charlie  35     Paris  95000        Rome
3    David  28     Tokyo  62000      Sydney
4      Eve  22    Mumbai  58000     Toronto

In [54]:
df.drop("Destination", axis=1, inplace=True)
df

      Name Age      City Salary
0    Alice  25  New York  70000
1      Bob  30    London  85000
2  Charlie  35     Paris  95000
3    David  28     Tokyo  62000
4      Eve  22    Mumbai  58000

### Selecting Row

In [55]:
df.loc[[0, 4]]

    Name Age      City Salary
0  Alice  25  New York  70000
4    Eve  22    Mumbai  58000

### Selecting Subsets of Rows and Columns

In [56]:
 df.loc[[0, 4]][["City", "Salary"]]

       City Salary
0  New York  70000
4    Mumbai  58000

In [57]:
 df.loc[[2, 3]][["Name", "Age"]]

      Name Age
2  Charlie  35
3    David  28

### Conditional Selection

In [58]:
df["Age"] = df["Age"].astype(int)

In [59]:
df[df["Age"] > 30]

      Name  Age   City Salary
2  Charlie   35  Paris  95000

# Missing Data

In [61]:
data = [
    {'Name': 'Alice',   'Age': 25,   'City': 'New York', 'Salary': 70000},
    {'Name': 'Bob',     'Age': None, 'City': 'London',   'Salary': 85000}, # Missing Age
    {'Name': 'Charlie', 'Age': 35,   'City': 'Paris',    'Salary': np.nan}, # Missing Salary
    {'Name': 'David',   'Age': 28,   'City': None,       'Salary': 62000}, # Missing City
    {'Name': None,   'Age': 22,   'City': 'Mumbai',   'Salary': 58000}
]

In [62]:
df = pd.DataFrame(data)

In [63]:
df

      Name   Age      City   Salary
0    Alice  25.0  New York  70000.0
1      Bob   NaN    London  85000.0
2  Charlie  35.0     Paris      NaN
3    David  28.0       NaN  62000.0
4      NaN  22.0    Mumbai  58000.0

In [64]:
df.isna()

    Name    Age   City  Salary
0  False  False  False   False
1  False   True  False   False
2  False  False  False    True
3  False  False   True   False
4   True  False  False   False

In [65]:
df.isna().sum()

Name      1
Age       1
City      1
Salary    1
dtype: int64

In [66]:
df.isna().any()

Name      True
Age       True
City      True
Salary    True
dtype: bool

### Removing Missing Data

In [67]:
df

      Name   Age      City   Salary
0    Alice  25.0  New York  70000.0
1      Bob   NaN    London  85000.0
2  Charlie  35.0     Paris      NaN
3    David  28.0       NaN  62000.0
4      NaN  22.0    Mumbai  58000.0

In [68]:
df.dropna()

    Name   Age      City   Salary
0  Alice  25.0  New York  70000.0

In [75]:
df.dropna(thresh=2)

      Name   Age      City   Salary
0    Alice  25.0  New York  70000.0
1      Bob   NaN    London  85000.0
2  Charlie  35.0     Paris      NaN
3    David  28.0       NaN  62000.0
4      NaN  22.0    Mumbai  58000.0

### Filling the missing Data

In [76]:
df.fillna(0)

      Name   Age      City   Salary
0    Alice  25.0  New York  70000.0
1      Bob   0.0    London  85000.0
2  Charlie  35.0     Paris      0.0
3    David  28.0         0  62000.0
4        0  22.0    Mumbai  58000.0

In [79]:
df["Name"] = df["Name"].fillna("Unknown")
df["City"] = df["City"].fillna("whatsit")

In [80]:
df

      Name   Age      City   Salary
0    Alice  25.0  New York  70000.0
1      Bob   NaN    London  85000.0
2  Charlie  35.0     Paris      NaN
3    David  28.0   whatsit  62000.0
4  Unknown  22.0    Mumbai  58000.0

# Merging, joining, Concatation

### Merge 2 DataFrames

In [81]:
emp_data = {
    'Emp_ID': [101, 102, 103, 104, 105],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'City': ['New York', 'London', 'Paris', None, 'Mumbai']
}

salary_data = {
    'Emp_ID': [101, 102, 103, 104, 105],
    'Salary': [70000, 85000, np.nan, 62000, 58000],
    'Dept': ['IT', 'HR', 'IT', 'Finance', 'Marketing']
}

df_employee = pd.DataFrame(emp_data)
df_salary = pd.DataFrame(salary_data)

In [84]:
df_employee

   Emp_ID     Name      City
0     101    Alice  New York
1     102      Bob    London
2     103  Charlie     Paris
3     104    David       NaN
4     105      Eve    Mumbai

In [83]:
df_salary

   Emp_ID   Salary       Dept
0     101  70000.0         IT
1     102  85000.0         HR
2     103      NaN         IT
3     104  62000.0    Finance
4     105  58000.0  Marketing

In [91]:
pd.merge(df_employee, df_salary, on="Emp_ID", how="inner")

   Emp_ID     Name      City   Salary       Dept
0     101    Alice  New York  70000.0         IT
1     102      Bob    London  85000.0         HR
2     103  Charlie     Paris      NaN         IT
3     104    David       NaN  62000.0    Finance
4     105      Eve    Mumbai  58000.0  Marketing

In [92]:
pd.merge(df_employee, df_salary, on="Emp_ID", how="outer")

   Emp_ID     Name      City   Salary       Dept
0     101    Alice  New York  70000.0         IT
1     102      Bob    London  85000.0         HR
2     103  Charlie     Paris      NaN         IT
3     104    David       NaN  62000.0    Finance
4     105      Eve    Mumbai  58000.0  Marketing

In [93]:
pd.concat([df_employee, df_salary])

   Emp_ID     Name      City   Salary       Dept
0     101    Alice  New York      NaN        NaN
1     102      Bob    London      NaN        NaN
2     103  Charlie     Paris      NaN        NaN
3     104    David       NaN      NaN        NaN
4     105      Eve    Mumbai      NaN        NaN
0     101      NaN       NaN  70000.0         IT
1     102      NaN       NaN  85000.0         HR
2     103      NaN       NaN      NaN         IT
3     104      NaN       NaN  62000.0    Finance
4     105      NaN       NaN  58000.0  Marketing

# Group by Aggregation

In [96]:
dates = pd.date_range(start='2024-01-01', periods=8)

data = {
    'Category': ['Electronics', 'Furniture', 'Electronics', 'Groceries', 
                 'Furniture', 'Electronics', 'Groceries', 'Electronics'],
    'Store': ['North', 'South', 'North', 'West', 'East', 'South', 'West', 'North'],
    'Sales': [1200.50, 450.00, np.nan, 150.75, 2100.00, 300.00, 85.00, 500.25],
    'Quantity': [3, 1, 2, 10, 5, 2, np.nan, 4],
    'Date': dates,
}

df = pd.DataFrame(data)

In [97]:
df

      Category  Store    Sales  Quantity       Date
0  Electronics  North  1200.50       3.0 2024-01-01
1    Furniture  South   450.00       1.0 2024-01-02
2  Electronics  North      NaN       2.0 2024-01-03
3    Groceries   West   150.75      10.0 2024-01-04
4    Furniture   East  2100.00       5.0 2024-01-05
5  Electronics  South   300.00       2.0 2024-01-06
6    Groceries   West    85.00       NaN 2024-01-07
7  Electronics  North   500.25       4.0 2024-01-08

In [99]:
df.groupby("Category")["Sales"].sum()

Category
Electronics    2000.75
Furniture      2550.00
Groceries       235.75
Name: Sales, dtype: float64

In [100]:
df.groupby("Store")["Sales"].sum()

Store
East     2100.00
North    1700.75
South     750.00
West      235.75
Name: Sales, dtype: float64

### Group by multiple columns

In [103]:
df.groupby(["Category", "Store"])["Sales"].sum()

Category     Store
Electronics  North    1700.75
             South     300.00
Furniture    East     2100.00
             South     450.00
Groceries    West      235.75
Name: Sales, dtype: float64

### Aggregation

In [102]:
df.groupby("Store")["Sales"].mean()

Store
East     2100.000
North     850.375
South     375.000
West      117.875
Name: Sales, dtype: float64

# 🥅 Pivot Tables

In [104]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South'] * 5,
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice'] * 5
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)

In [105]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    235     77   John  January      Q1
1  2023-01-02       B   West    708     85   Mary  January      Q1
2  2023-01-03       C  North    186     45    Bob  January      Q1
3  2023-01-04       D  South    882     40  Alice  January      Q1
4  2023-01-05       A   East    116     34   John  January      Q1
5  2023-01-06       B   West    639     32   Mary  January      Q1
6  2023-01-07       C  North    114     58    Bob  January      Q1
7  2023-01-08       D  South    785     37  Alice  January      Q1
8  2023-01-09       A   East    541     62   John  January      Q1
9  2023-01-10       B   West    118     17   Mary  January      Q1
10 2023-01-11       C  North    228     71    Bob  January      Q1
11 2023-01-12       D  South    284     79  Alice  January      Q1
12 2023-01-13       A   East    479     55   John  January      Q1
13 2023-01-14       B   West    501     94   Mary  January      Q1
14 2023-01-15       C  North    328     55    Bob  January      Q1
15 2023-01-16       D  South    861     88  Alice  January      Q1
16 2023-01-17       A   East    891     89   John  January      Q1
17 2023-01-18       B   West    353     27   Mary  January      Q1
18 2023-01-19       C  North    409     48    Bob  January      Q1
19 2023-01-20       D  South    978     35  Alice  January      Q1

In [109]:
pd.pivot_table(df, values="Sales", index="Region", columns="Product")

Product      A      B      C      D
Region
East     452.4    NaN    NaN    NaN
North      NaN    NaN  253.0    NaN
South      NaN    NaN    NaN  758.0
West       NaN  463.8    NaN    NaN

In [111]:
pivot = pd.pivot_table(df, values=["Sales", "Units"], index="Region", columns="Product")

In [112]:
pivot

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     452.4    NaN    NaN    NaN  63.4   NaN   NaN   NaN
North      NaN    NaN  253.0    NaN   NaN   NaN  55.4   NaN
South      NaN    NaN    NaN  758.0   NaN   NaN   NaN  55.8
West       NaN  463.8    NaN    NaN   NaN  51.0   NaN   NaN

In [113]:
pivot.fillna(0)

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     452.4    0.0    0.0    0.0  63.4   0.0   0.0   0.0
North      0.0    0.0  253.0    0.0   0.0   0.0  55.4   0.0
South      0.0    0.0    0.0  758.0   0.0   0.0   0.0  55.8
West       0.0  463.8    0.0    0.0   0.0  51.0   0.0   0.0

In [114]:
pivot

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     452.4    NaN    NaN    NaN  63.4   NaN   NaN   NaN
North      NaN    NaN  253.0    NaN   NaN   NaN  55.4   NaN
South      NaN    NaN    NaN  758.0   NaN   NaN   NaN  55.8
West       NaN  463.8    NaN    NaN   NaN  51.0   NaN   NaN

### Cross Tables

In [115]:
pd.crosstab(df["Region"], df["Product"])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

# Operations

In [116]:
data = {
    'ID': [1, 2, 3, 4, 5],
    'Product': ['Phone', 'Laptop', 'Tablet', 'Watch', 'TV'],
    'Price': [500, 1200, np.nan, 250, 800],
    'Quantity': [10, 5, 8, 15, 2]
}

df = pd.DataFrame(data)

In [117]:
df

   ID Product   Price  Quantity
0   1   Phone   500.0        10
1   2  Laptop  1200.0         5
2   3  Tablet     NaN         8
3   4   Watch   250.0        15
4   5      TV   800.0         2

In [119]:
df.shape

(5, 4)

In [120]:
df.columns

Index(['ID', 'Product', 'Price', 'Quantity'], dtype='str')

In [124]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        5 non-null      int64
 1   Product   5 non-null      str
 2   Price     4 non-null      float64
 3   Quantity  5 non-null      int64
dtypes: float64(1), int64(2), str(1)
memory usage: 292.0 bytes

In [125]:
df.describe()

             ID       Price   Quantity
count  5.000000     4.00000   5.000000
mean   3.000000   687.50000   8.000000
std    1.581139   409.01304   4.949747
min    1.000000   250.00000   2.000000
25%    2.000000   437.50000   5.000000
50%    3.000000   650.00000   8.000000
75%    4.000000   900.00000  10.000000
max    5.000000  1200.00000  15.000000

In [126]:
def square(x):
    return x ** 2

In [127]:
df["Price"] = df["Price"].apply(square)

0     250000.0
1    1440000.0
2          NaN
3      62500.0
4     640000.0
Name: Price, dtype: float64